/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface StopwatchLap {
  totalTime?: number;
  startTime?: number | null;
  isRunning?: boolean;
  isEnded?: boolean;
  hours?: number;
  minutes?: number;
  seconds?: number;
  limitMiliseconds?: number;
  backwards?: boolean;
}
