/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Stopwatch {
  /**
   * This interface was referenced by `Stopwatch`'s JSON-Schema definition
   * via the `patternProperty` ".+".
   */
  [k: string]: {
    totalTime?: number;
    startTime?: number | null;
    isRunning?: boolean;
    hours?: number;
    minutes?: number;
    seconds?: number;
    limitMiliseconds?: number;
    backwardsMiliseconds?: boolean;
    [k: string]: unknown;
  };
}
