/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type MatchActions = MatchAction[];

export interface MatchAction {
  id: string;
  gmtTimestamp: number;
  matchTime: number;
  team: "LOCAL" | "VISITOR";
  action:
    | "GOAL"
    | "TIMEOUT"
    | "WARNING"
    | "MATCH_START"
    | "MATCH_END"
    | "OTHER";
  payload?: unknown;
}
