/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Scores {
  local?: {
    goals?: number;
    timeouts?: number;
    warnings?: {
      time?: number;
      type?: "2minute" | "yellow-card" | "red-card" | "blue-card";
      player?: number | string | null;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  visitor?: {
    goals?: number;
    timeouts?: number;
    warnings?: {
      time?: number;
      type?: "2minute" | "yellow-card" | "red-card" | "blue-card";
      player?: number | string | null;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
}
